eclipse/ceylon-lang.org

documentation/1.1/faq/language-design.md

- Optional types are `Null|T`, not `Nothing|T`
- “its” → “it’s” (“it is simpler”)

Two minor fixes to language design FAQ

---

documentation/1.1/tour/attributes-control-structures.md

Updating this "Tour of Ceylon" doc section:
http://ceylon-lang.org/documentation/1.1/tour/attributes-control-structures/

Fix minor spacing inconsistencies and grammar typos

---

documentation/1.1/roadmap.md
js/common.js

The milestone names ("1.3", "1.3.0") are turned into links to the Github milestone page, allowing users to easily see all open issues.

Roadmap: turn milestone names into links

---

documentation/1.1/reference/operator/unary_plus.md

See also #341.
Note: another open question, which this PR doesn’t address, is whether the preceding sentence is still correct:
> The unary `+` operator is [polymorphic](#{page.doc_root}/reference/operator/operator-polymorphism). The meaning of `+` depends on [`Invertible`](#{site.urls.apidoc_1_1}/Invertible.type.html) interface
It’s still *kinda* polymorphic, since `+x` is only legal for `Invertible x`, but the result/meaning doesn’t depend on the implementation of `x` – it’s always simply `x`.

Fix copy+paste error in unary plus reference

---

documentation/1.1/tour/sequences.md

I think this fix is missing from c22a4b3.
This came up on the ceylon-users mailing list: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ceylon-users/PPzRaDe-H80/hbIfT5dbCQAJ

Fix reference to deleted function

---

documentation/1.2/reference/expression/meta-reference.md

- lowercase constructor names
- changed metamodel types
- use constructor that actually exists
- add `` `interface` `` syntax
- make containing type example non-interactive
see https://groups.google.com/d/msg/ceylon-users/_tQM7bVqy7U/jRory5YmEQAJ

Update meta reference

---

documentation/1.2/tour/sequences.md
documentation/1.2/tour/typeinference.md

BTW: The documentation for class Range mentions functions makeSpan() and makeMeasure(), but the corresponding links point to span() and measure(). I guess these functions were renamed and the old names somehow survived in the doc comments...

Minor change due to Range being an abstract class nowadays

---

code/issues.md

(We might also want to remove the link to the known-issues page, since we’re not *actually* maintaining it, but that’s separate.)

Update issues page for OBR and IDEs

---

documentation/1.1/index.md
documentation/1.1/introduction.md
documentation/1.2/index.md
documentation/1.2/introduction.md

The Ceylon Core Manual for Vert.x appears to have moved.

Fix Vert.x links.

---

documentation/1.2/reference/interoperability/osgi.md
documentation/1.2/tour/interop.md

(This is a fixup for #398.)
Indentation was being interpreted incorrectly, there were some spelling errors, some links were broken, and ceylon-lang.org's Markdown processor doesn't support ```` ``` ```` code blocks or automatic links.
There's also a remaining problem: the code blocks get Try Online links. We can't currently remove those without breaking the markup, at least not without more work than I can put in right now.

Fixes for OSGi documentation

---

documentation/1.2/tour/index.md

The project at the old link has been deprecated.

fix ceylon-dist readme link

---

js/common.js

Instead of linking to the full URL + anchor, just link to the anchor. No need to reload the site for this. I suggested this in #432 and then didn’t do anything about it for months, and I don’t even know why I implemented the full URL version in #309 in the first place – you can see that the actual fix, aside from a comment update, is purely to remove some code – but anyways, it’s better now, so there we are.
---
Putting this up for review in case someone wants to look at it, but otherwise I’ll just merge this tomorrow or so.

Improve anchor links

---

documentation/1.2/reference/operator/unary_plus.md

In the past, the unary `+` used to be equivalent to `.positiveValue`. This is no longer true. `positiveValue` doesn’t even exist anymore!

update information about the unary plus

---

documentation/1.3/reference/statement/specification.md

The original link to [../destructuring](https://ceylon-lang.org/documentation/1.3/reference/statement/destructuring) gave a 404.

fix link to destructuring in documentation

---

code/source.md

This is for the code/source file. The "Ceylon Eclipse IDE plugin" section renamed and moved, so the old link doesn't work anymore.

remove broken link from table of contents

---

download-archive.html.haml

Commit 99a65b8 removed the line break, which made the anchor empty. This change restores it. The alternative would be to remove the link altogether.

Restored link to release announcement blog post

---

documentation/1.0/faq/language-design.md
documentation/1.1/faq/language-design.md
documentation/1.2/faq/language-design.md
documentation/1.3/faq/language-design.md

Grammar error: The word "something" was duplicated. Mistakenly I think.

Grammar fix: Removed duplicate word

---

documentation/1.1/reference/annotation/doc.md
documentation/1.1/reference/annotation/license.md
documentation/1.1/reference/annotation/native.md
documentation/1.1/reference/annotation/optional.md
documentation/1.1/reference/annotation/see.md
documentation/1.1/reference/annotation/tagged.md
documentation/1.1/reference/annotation/throws.md
documentation/1.1/reference/annotation/variable.md
documentation/1.2/reference/annotation/aliased.md
documentation/1.2/reference/annotation/doc.md
documentation/1.2/reference/annotation/license.md
documentation/1.2/reference/annotation/native.md
documentation/1.2/reference/annotation/optional.md
documentation/1.2/reference/annotation/see.md
documentation/1.2/reference/annotation/serializable.md
documentation/1.2/reference/annotation/suppressWarnings.md
documentation/1.2/reference/annotation/tagged.md
documentation/1.2/reference/annotation/throws.md
documentation/1.2/reference/annotation/variable.md
documentation/1.3/reference/annotation/doc.md
documentation/1.3/reference/annotation/license.md
documentation/1.3/reference/annotation/native.md
documentation/1.3/reference/annotation/optional.md
documentation/1.3/reference/annotation/see.md
documentation/1.3/reference/annotation/serializable.md
documentation/1.3/reference/annotation/suppressWarnings.md
documentation/1.3/reference/annotation/tagged.md
documentation/1.3/reference/annotation/throws.md
documentation/1.3/reference/annotation/variable.md

Not all links to annotation api documantation were formatted similarily. I fixed the few odd references t, so that all have same wording now.

More small fixes to annotation reference documentation

---

documentation/1.3/reference/literal/string.md

The (reference)[https://ceylon-lang.org/documentation/reference/literal/string/] states currently that backticks have to be escaped, but 
```
print("Hello `world`");
```
**does** print `` "Hello `world` ``. According to Section 2.4.3 ("String literals") of the (language specification)[https://ceylon-lang.org/documentation/1.3/spec/pdf/ceylon-language-specification.pdf], A sequence of two backticks is used to delimit an interpolated expression embedded in a string template. Therefore, double backticks should be escaped instead.
See issue #455

Double backticks should be escaped instead of single backticks

---

code/architecture.md

It looks like it was forgotten to update the repository names when several repositories were merged in 2015.
I tried to fix this to the best of my knowledge, but I'm not sure if this is still up-to-date – it might be that some content was spread over several directories when merging the repositories. Please check this.
Also, should I add actual hyperlinks to the repositories/directories in there?

fix repository mentions after the repo merge

---

documentation/1.3/tour/modules.md

it expects a declaration, not a type.
fixes https://github.com/ceylon/ceylon-lang.org/issues/490
I'm not sure if this PR should be against master or 1.3.3?

Corrected example for `service` annotation

---

documentation/1.3/reference/statement/import.md

@drhagen pointed out [on StackOverflow][1] that a module containing a `math` package is nowhere to be found. I assume it’s intended to be fictitious (the `ceylon.math` in the SDK lacks `Complex`), so add `org.example` to the package name to clarify this and bring the import in line with the other imports below.
Also, while we’re at it, consistently use `org.example` instead of `com.example`.
[1]: https://stackoverflow.com/q/49592547/1420237

Clarify fictitious imported module
